### ISSUE TITLE
Dumpfile v 1.84_0.14 CommandersLog

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/RegulatedNoise#26] opened 2015-04-10 02:22 UTC
Clicking on the Commanders Log Tab produces dump

https://www.dropbox.com/s/ufondi4k4psze99/CommandersLogRegulatedNoiseDump.zip?dl=0

**Comment by Duke-Jones** [comment] 2015-04-15 15:47
do this happen often ?
do you have the RegulatedNoiseSettings.xml open in another editor or anything similar  ?

**Comment by sutex** [comment] 2015-04-16 23:59
Often ? only if I just keep clicking on Commanders Log Tab , then yes , it happens all the time. here is another dumb file , have no editors open
https://www.dropbox.com/s/tknbuxaea2hax9g/Commander%27s%20Log%20%2017th%20RegulatedNoiseDump.zip?dl=0

**Comment by Duke-Jones** [comment] 2015-04-17 08:49
where exactly do you click ?
I can't reproduce this behaviour :(

**Comment by sutex** [comment] 2015-04-17 09:17
On the tab , that says Commanders Log... Just open RN and tried again  BUT it didn't crash , did twice before , If RN crashes twice after doing one thing I'll send the dump file , otherwise I don't worry about it

**Comment by Duke-Jones** [comment] 2015-04-19 14:49
I close this for the moment

**Closed as completed by Duke-Jones** 2015-04-19 14:49 UTC
Labels: bug
