### ISSUE TITLE
Application constantly crashes while OCRing multiple Screenshots in one row

### ISSUE THREAD

**Issue by khasrahh** [Duke-Jones/RegulatedNoise#23] opened 2015-04-06 10:38 UTC
I have experienced several crashes of the app while OCRing multiple market screenshots (at least 4 in queue) with version 1.84_0.12.

Here's a link to the resulting dump file:
https://onedrive.live.com/redir?resid=6C57B6C9EE6013E1!854&authkey=!AHiQjASBEiC2DEk&ithint=file%2cdmp

**Comment by Duke-Jones** [comment] 2015-04-06 11:45
Please test the lastest prerelease (0.13_4)
I hope the problem is gone with it. 
Otherwise you can leave a litte "no" post here ;-)

**Comment by Duke-Jones** [comment] 2015-04-06 20:22
as I've released the v1.84_0.13 I close this issue.
If it's still crashes the same way reopen this issue please

**Closed as completed by Duke-Jones** 2015-04-06 20:22 UTC
Labels: bug
